title: Malvi's Blog
author: gaganmalvi
subtitle: My adventures

url: "https://malvi.ml"
baseurl: "/blog"

footer_only_homepage: true
footer_url: "https://github.com/gaganmalvi"
footer_text: "GitHub Profile"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Website"
   absolute-link: "https://malvi.ml/"
